### PR TITLE
Rename TimerCursorMixin.ts to TimerCursorMixin.d.ts

### PR DESCRIPTION
**Pull request by imme-emosol**

### CODE REVIEW

**Comment by JanMiksovsky** [comment]
Thanks for catching this and for submitting a fix.

Heads up that I’ll be traveling for the next few weeks without a computer — I’ll land this when I’m back. Sorry for the delay.

**Comment by JanMiksovsky** [comment]
Thanks again

**Comment by imme-emosol** [comment]
By the way, I found it by accident, because I used TypeScript to copy elix from node_modules into the directory that the webserver exposes.. In doing so, TypeScript attempted to compile everything and notified about this.

**Comment by JanMiksovsky** [comment]
Good to know.

It's too bad that our existing use of the TypeScript compiler to check types within the project doesn't catch problems like this. Perhaps there is a way we could catch these problems ourselves, but my TS skills are insufficient. In any event, since this is the first bug like this I've seen (or, at least, seen in a very long time), we can hope we don't see too many more problems like it.

**Comment by imme-emosol** [comment]
I recently started with TS as well, so perhaps it makes no sense at all. But I do like that I managed to get something working without a bundler such as webpack, rollup etc.

This is what I used in a `tsconfig.elix.json` file, for copying the files from `<project-root>/node_modules/elix/` into `<project-root>/public/assets/node_modules/elix/`

In my `package.json` I then defined a script to call typescript to compile elix into elix.
```js
{
// [...]
   "scripts": {
// [...]
        "build:ts": "pnpm run build:ts:lib && pnpm run build:ts:main ",
        "build:ts:lib": "tsc --build tsconfig.elix.json ",
        "build:ts:main": "tsc --build tsconfig.json ",
// [...]
    }
// [...]
}
```

```js
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ES2020",
    "noEmitOnError": true,
    "outDir": "../public/assets/node_modules/elix",
    "removeComments": true,
    "rootDir": "node_modules/elix",
    "skipLibCheck": true,
    "sourceMap": true,
//    "sourceRoot": "node_modules/elix",
    "sourceRoot": "file:///absolute_path_to_project_with_elix_npm_package/node_modules/elix",
    "strict": true,
    "target": "ES2020"
  },
  "exclude": [
  ],
  "include": [
    "node_modules/elix/define/**/*.js",
    "node_modules/elix/src/base/**/*.js",
    "node_modules/elix/src/core/**/*.js",
    "node_modules/elix/src/plain/**/*.js",
    "node_modules/elix/src/elix.js"
  ]
}
```

**Pull request merged**
