### PR TITLE
Initial implementation of SelectionAriaMixin, ShadowTemplateMixin, and ClickSelectionMixin

### PR DESCRIPTION
**Pull request by JanMiksovsky**
This PR introduces three new mixins related to our work towards a list box component:

1. SelectionAriaMixin. Covered by the [ARIA selection mixin RFC](https://github.com/elix/rfcs/pull/4).
2. ShadowTemplateMixin. Covered by the [Shadow template mixin RFC](https://github.com/elix/rfcs/pull/5).
3. ClickSelectionMixin. Not yet covered by an RFC pending discussion on Slack.

This PR builds on the separate [single-selection PR](https://github.com/elix/elix/pull/2), which should land first.

This PR includes a sample-list-box demo element that uses the above mixins to construct a very basic list box component. This is intended as a small but important step forward towards a real list box component.

In addition to the above mixins, this PR includes the following:
* Introduction of test helpers to mock user interactions like clicks.
* Removal of elix-sample-element, since the sample-list-box demo is a more complete demonstration of the mixin approach to component development.
* Adoption of the [webcomponents-platform](https://github.com/webcomponents/webcomponents-platform) polyfills for various ES6 features to support IE 11.
* A polyfill for the ES6 `Symbol` class for IE 11.
* A `microtask` helper for delaying execution of tasks to the next microtask.

### CODE REVIEW

**Comment by JanMiksovsky** [comment]
BTW, I've posted the sample-list-box demo on https://janmiksovsky.github.io/elix/elements/demos/listBox.html in case anyone wants to see it in action.

**Comment by JanMiksovsky** [comment]
Since there's a lot of changed files in this PR, the three files to focus on are:
[SelectionAriaMixin.js](https://github.com/JanMiksovsky/elix/blob/list-mixins-1/elements/elix-mixins/src/SelectionAriaMixin.js)
[ShadowTemplateMixin.js](https://github.com/JanMiksovsky/elix/blob/list-mixins-1/elements/elix-mixins/src/ShadowTemplateMixin.js)
[ClickSelectionMixin.js](https://github.com/JanMiksovsky/elix/blob/list-mixins-1/elements/elix-mixins/src/ClickSelectionMixin.js)

Also, I've posted a separate [Polymer list box demo](https://github.com/JanMiksovsky/polymer-demos/blob/master/src/ListBox.js) of these mixins applied to a Polymer 2.0. The result is essentially the same as the list box demo above, but using `Polymer.Element` and various Polymer idioms instead of plain `HTMLElement` and the plain JavaScript way of doing things.

**Comment by JanMiksovsky** [comment]
Since `SelectionAriaMixin` is intended to support screen readers, here's a way for Mac users to test screen reader support:
* Open the plain JS [list box demo](https://janmiksovsky.github.io/elix/elements/demos/listBox.html) or the Polymer demo above.
* Press Command+F5 to turn on the VoiceOver screen reader. A robotic voice will begin talking.
* Click on the list box, or navigate to it by pressing the Tab key.
* The screen reader will say that you're in a list with _n_ items.
* Press the Up and Down keys to navigate around the list. The screen reader will tell you which item you're on.
* Close your eyes and pick an item with the keyboard! That's the real screen reader user experience.
* Turn the annoying robotic voice off by pressing Command+F5 again. Enjoy the silence, and reflect on how challenging it is for people to navigate the web with a screen reader.

**Comment by chiefcll** [comment]
👍

**Pull request merged**
